authors:
  Joey:
    name: Joey E.
    description: Full-time nerd
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQFnsyOakSLNaQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1605527432950?e=1741824000&v=beta&t=YSRDeNQ4mtvc8zO2FNgnQRhuwQ-lwU5QOmyxeKoT98M